### ISSUE TITLE
Copy button Overlapping

### ISSUE THREAD

**Issue by AlishahMughal123** [Asterium-Blockchain/cardano-explorer#6]
<img width="1049" alt="image" src="https://user-images.githubusercontent.com/52525188/170249439-e5ee8dee-4415-4419-b133-e4711cad8119.png">

**Comment by MartinSchere** [comment]
Thanks a lot!

**Comment by MartinSchere** [comment]
Will take a look as soon as I can

**Comment by AlishahMughal123** [comment]
You're welcome, Martin.
